# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título do evento')),
                ('date', models.DateField(blank=True, verbose_name='Data do evento')),
                ('text', models.TextField(verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline/images', verbose_name='Imagem de apresentação')),
                ('legend_image', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda da imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento da linha do tempo',
                'verbose_name_plural': 'Eventos da linha do tempo',
                'ordering': ['date'],
            },
        ),
    ]
