# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-date'], 'verbose_name': 'Evento da linha do tempo', 'verbose_name_plural': 'Eventos da linha do tempo'},
        ),
    ]
