# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='alert/images', verbose_name='Imagem para o alerta')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('expired_at', models.DateField(blank=True, null=True, verbose_name='Data de expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Alerta',
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
