# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 13:26
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('username', models.CharField(help_text='Um nome curto e único que será usado para identificá-lo', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'Informe um nome de usuário válidoEste valor deve conter apenas letras, digitose os caracteres: @|.|+|-|_', 'invalid')], verbose_name='Usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='Registro geral (RG)')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Código de pessoa fisica (CPF)')),
                ('sexo', models.CharField(blank=True, choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Não fornecer')], max_length=1, null=True, verbose_name='Sexo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='É da equipe')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'verbose_name': 'Usuário',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
