# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('0', 'Masculino'), ('1', 'Feminino'), ('2', 'Não fornecer')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
