# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Nome da Vila ou Comunidade')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Sobre a comunidade')),
                ('lat', models.CharField(blank=True, max_length=100, verbose_name='Latitude')),
                ('lng', models.CharField(blank=True, max_length=100, verbose_name='Longitude')),
                ('slug', models.SlugField(help_text="'slug' é um identificador único que será mostrado na url", max_length=500, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Comunidade/Vila',
                'ordering': ['title'],
                'verbose_name_plural': 'Comunidades/Vilas',
            },
        ),
    ]
