# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Legenda da imagem'),
        ),
        migrations.AddField(
            model_name='community',
            name='credit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cŕeditos da imagem'),
        ),
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='communities/images', verbose_name='Imagem para o mapa das comunidades'),
        ),
        migrations.AddField(
            model_name='community',
            name='textMap',
            field=models.TextField(blank=True, help_text='Esse campo deve ser preenchido com o resumo sobre a comunidade e será apresentado no mapa com todas as comunidades', null=True, verbose_name='Resumo da comunidade'),
        ),
    ]
