# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20170904_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/images', verbose_name='Imagem para página da comunidade')),
                ('credit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Créditos da imagem')),
                ('caption', models.CharField(blank=True, max_length=300, null=True, verbose_name='Legenda da imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name_plural': 'Fotos das comunidades',
                'verbose_name': 'Fotos da comunidade',
            },
        ),
        migrations.AddField(
            model_name='community',
            name='photos',
            field=models.ManyToManyField(to='communities.CommunityPhoto', verbose_name='Fotos da comunidade'),
        ),
    ]
