# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20170921_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityphoto',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome da foto. Formato: Nome foto - Nome comunidade'),
        ),
    ]
