# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_communityphoto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='communities.CommunityPhoto', verbose_name='Fotos da comunidade'),
        ),
    ]
