# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome da pessoa')),
                ('testimony', models.TextField(verbose_name='Depoimento')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimony/images', verbose_name='Imagem de depoimento')),
                ('legend_image', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda da imagem')),
                ('exPlace', models.CharField(max_length=500, verbose_name='Local onde morava')),
                ('place', models.CharField(max_length=500, verbose_name='Moradia atual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
    ]
