# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('subCategory', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria da notícia',
                'verbose_name_plural': 'Categorias das notícias',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('subTitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('published_at', models.DateField(verbose_name='Data de publicação')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images', verbose_name='Imagem de capa para a Notícia')),
                ('legendImage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda da Imagem')),
                ('creditsImage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Creditos da imagem')),
                ('noticeOrigin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonte da notícia')),
                ('slug', models.SlugField(help_text="'slug' é um identificador único que será mostrado na url", max_length=500, unique=True, verbose_name='Identificador')),
                ('is_public', models.BooleanField(default=True, help_text='Somente as notícias marcadas como públicas serão apresentadas no site.', verbose_name='É Pública ?')),
                ('expired_at', models.DateField(blank=True, null=True, verbose_name='Data de expiração da notícia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('categoryNews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.CategoryNews')),
            ],
            options={
                'verbose_name': 'Notícia',
                'ordering': ['-published_at', 'legendImage'],
                'verbose_name_plural': 'Notícias',
            },
        ),
    ]
