# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', 'legendImage'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='credits_image',
            new_name='creditsImage',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='legend_image',
            new_name='legendImage',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='notice_origin',
            new_name='noticeOrigin',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='sub_title',
            new_name='subTitle',
        ),
    ]
