# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de publicação'),
        ),
    ]
