# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170926_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='authorText',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto por'),
        ),
    ]
