# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170821_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='expired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de expiração da notícia'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateField(null=True, verbose_name='Data de publicação'),
        ),
    ]
