# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images', verbose_name='Imagem de capa para a Notícia')),
                ('legendImage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda da Imagem')),
                ('creditsImage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Creditos da imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['news'],
                'verbose_name': 'Foto da notícia',
                'verbose_name_plural': 'Foto da Notícias',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='is_formated',
            field=models.BooleanField(default=False, help_text='Marcar esse campo somente quando a notícia estiver formatada', verbose_name='Formatada ?'),
        ),
        migrations.AddField(
            model_name='photonews',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
