# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170921_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='face',
            field=models.ImageField(default=None, upload_to='/gallery/faces', verbose_name='Rosto da galeria'),
            preserve_default=False,
        ),
    ]
