# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170825_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='published_at',
            field=models.DateField(null=True, verbose_name='Data de publicação'),
        ),
    ]
