# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='published_at',
        ),
    ]
