# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='gallery.Photo'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='gallery.Video'),
        ),
    ]
