# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='Foi respondido?'),
        ),
    ]
