# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título da ata de reunião')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ppt', models.FileField(upload_to='apresentacao_reuniao/%Y/%m/%d/')),
                ('pdf', models.FileField(upload_to='ata_reuniao/%Y/%m/%d/')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data da Ata de reunião')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': 'Atas de Reuniões',
                'verbose_name': 'Ata de Reunião',
            },
        ),
    ]
