# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meetingType',
            field=models.CharField(default=None, max_length=500, verbose_name='Tipo de reuniao'),
            preserve_default=False,
        ),
    ]
