# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_meetingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título do edital')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('notice', models.FileField(upload_to='edital/%Y/%m/%d/')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data do edital')),
                ('noticeType', models.CharField(choices=[('', ''), ('', ''), ('', '')], max_length=500, verbose_name='Tipo de edital')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name_plural': 'Editais',
                'verbose_name': 'Edital',
            },
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meetingType',
            field=models.CharField(choices=[('conselho-executivo', 'Conselho Executivo'), ('outro', 'Outros')], max_length=500, verbose_name='Tipo de reuniao'),
        ),
    ]
