# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20171027_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link externo para o edital'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticeType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.NoticeType', verbose_name='Tipo de edital'),
        ),
    ]
