# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20171027_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
        migrations.AddField(
            model_name='notice',
            name='publishDate',
            field=models.DateField(blank=True, null=True, verbose_name='Data da publicação'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.FileField(upload_to='edital/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
    ]
