# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome do documento')),
                ('typeDocument', models.CharField(max_length=500, verbose_name='Tipo do documento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('document', models.FileField(upload_to='documento/%Y/%m/%d/')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data do documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
                'verbose_name': 'Documento',
            },
        ),
    ]
